server:
  port: 8081

spring:
  application:
    name: ApiGateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false   # IMPORTANT

      routes:
        - id: AuthService
          uri: lb://AuthService
          predicates:
            - Path=/api/auth/**

        - id: UserService
          uri: lb://UserService
          predicates:
            - Path=/api/users/**

        - id: ChatService
          uri: lb://ChatService
          predicates:
            - Path=/ws/**

        - id: MessageService
          uri: lb://MessageService
          predicates:
            - Path=/api/messages/**

        - id: GroupService
          uri: lb://GroupService
          predicates:
            - Path=/api/groups/**

        - id: NotificationService
          uri: lb://NotificationService
          predicates:
            - Path=/api/notifications/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"